--EJERCICIO 2

--A

SELECT C.IDENTIFICACION, F.IBAN, R.SALDO, DI.ABREVIATURA, DI.CAMBIOEURO FROM CLIENTE C, FINTECH F, POOLED_ACCOUNT P, 
DEPOSITADA_EN D, REFERENCIA R, DIVISA DI
WHERE C.ID = F.CLIENTE_ID AND F.IBAN = P.IBAN AND D.POOLED_ACCOUNT_IBAN = P.IBAN
AND D.REFERENCIA_IBAN = R.IBAN AND R.DIVISA_ABREVIATURA = DI.ABREVIATURA

UNION

SELECT C.IDENTIFICACION, F.IBAN, R.SALDO, DI.ABREVIATURA, DI.CAMBIOEURO FROM CLIENTE C, FINTECH F, SEGREGADA S, REFERENCIA R, DIVISA DI
WHERE C.ID = F.CLIENTE_ID AND F.IBAN = S.IBAN AND S.IBAN_CUENTAREF = R.IBAN 
AND  R.DIVISA_ABREVIATURA = DI.ABREVIATURA;





 CREATE OR REPLACE VIEW V_SALDOS
 AS SELECT C.IDENTIFICACION, F.IBAN, R.SALDO, DI.ABREVIATURA, DI.CAMBIOEURO FROM CLIENTE C, FINTECH F, POOLED_ACCOUNT P, 
DEPOSITADA_EN D, REFERENCIA R, DIVISA DI
WHERE C.ID = F.CLIENTE_ID AND F.IBAN = P.IBAN AND D.POOLED_ACCOUNT_IBAN = P.IBAN
AND D.REFERENCIA_IBAN = R.IBAN AND R.DIVISA_ABREVIATURA = DI.ABREVIATURA

UNION

SELECT C.IDENTIFICACION, F.IBAN, R.SALDO, DI.ABREVIATURA, DI.CAMBIOEURO FROM CLIENTE C, FINTECH F, SEGREGADA S, REFERENCIA R, DIVISA DI
WHERE C.ID = F.CLIENTE_ID AND F.IBAN = S.IBAN AND S.IBAN_CUENTAREF = R.IBAN 
AND  R.DIVISA_ABREVIATURA = DI.ABREVIATURA;

SELECT * FROM V_SALDOS;
 
 
 
 
SELECT AU.IDENTIFICACION, E.RAZON_SOCIAL  FROM PERSONA_AUTORIZADA AU, AUTORIZACIÓN AUT , EMPRESA E, FINTECH F, POOLED_ACCOUNT P,
DEPOSITADA_EN D, REFERENCIA R, DIVISA DI
WHERE AU.ID = AUT.PERSONA_AUTORIZADA_ID AND E.ID = AUT.EMPRESA_ID AND F.CLIENTE_ID = E.ID
AND F.IBAN = P.IBAN AND P.IBAN = D.POOLED_ACCOUNT_IBAN AND D.REFERENCIA_IBAN = R.IBAN
AND  R.DIVISA_ABREVIATURA = DI.ABREVIATURA;
 
 --B
 --CREACIÓN DE LAS SECUENCIAS
 
 CREATE SEQUENCE SQ_CLIENTE START WITH 1
 INCREMENT BY 10;
 
 CREATE SEQUENCE SQ_PERSONA START WITH 1
 INCREMENT BY 10;
 
 --MODIFICACIONES HECHAS 
 
 --C
 --CREACION DE TRIGGER
 
 
CREATE SEQUENCE SQ_TRANSACCION
START WITH 1 
INCREMENT BY 1;
 
create or replace trigger TR_TRANSACCION
before insert on TRANSACCION
for each row

begin
    :new.id_único := SQ_TRANSACCION.NEXTVAL;
end;
/


CREATE TABLE PAGOS (ID_OP VARCHAR2 (50), N_TARJETA VARCHAR2(50));
 