CREATE OR REPLACE PACKAGE PK_GESTION_CUENTAS AS 
    PROCEDURE ABRIR_CUENTA (IBAN VARCHAR2, SWIFT VARCHAR2, TIPO_CUENTA VARCHAR2,
    IDE_CLIENTE NUMBER, CLASIFICACION VARCHAR2, IBAN_REFERENCIA VARCHAR2, COMISION NUMBER);
    
    
    PROCEDURE CIERRE_CUENTA (IBANN VARCHAR2, TIPO_CUENTA VARCHAR2, IBAN_REFERENCIA VARCHAR2);
    
    
    
END PK_GESTION_CUENTAS;
/


CREATE OR REPLACE PACKAGE BODY PK_GESTION_CUENTAS AS
    PROCEDURE ABRIR_CUENTA (IBAN VARCHAR2, SWIFT VARCHAR2, TIPO_CUENTA VARCHAR2,
    IDE_CLIENTE NUMBER, CLASIFICACION VARCHAR2, IBAN_REFERENCIA VARCHAR2,COMISION NUMBER)
    IS
    
    FILA VARCHAR(50);
    CLIENTE_NO_ENCONTRADO EXCEPTION;
    TIPO_NO_VALIDO EXCEPTION;
    CLIENTE_BAJA EXCEPTION;
    REFERENCIA_NO_ENCONTRADA EXCEPTION;
    
    BEGIN 
    
    SELECT COUNT(*) INTO FILA
    FROM CLIENTE
    WHERE ID = IDE_CLIENTE;
    
    IF FILA != '1' THEN
        RAISE CLIENTE_NO_ENCONTRADO;
    END IF;
    
    SELECT COUNT(*) INTO FILA
    FROM CLIENTE 
    WHERE ID = IDE_CLIENTE AND ESTADO = 'BAJA';
    
    IF FILA LIKE '1' THEN
        RAISE CLIENTE_BAJA;
    END IF;
    
    IF TIPO_CUENTA != 'POOLED' AND TIPO_CUENTA != 'SEGREGATED' THEN
        RAISE TIPO_NO_VALIDO;
    END IF;
    
    INSERT INTO CUENTA VALUES (IBAN, SWIFT);
    
    INSERT INTO FINTECH VALUES (IBAN, 'ACTIVA', SYSDATE, NULL, CLASIFICACION,
    IDE_CLIENTE);
    
    IF TIPO_CUENTA LIKE 'POOLED' THEN
        SELECT COUNT(*) INTO FILA
        FROM REFERENCIA
        WHERE IBAN = IBAN_REFERENCIA;
        
        IF FILA !=  '1' THEN
            RAISE REFERENCIA_NO_ENCONTRADA;
        END IF;
        INSERT INTO POOLED_ACCOUNT VALUES (IBAN);
        INSERT INTO DEPOSITADA_EN VALUES (0, IBAN, IBAN_REFERENCIA);
    END IF;
    
    IF TIPO_CUENTA LIKE 'SEGREGADA' THEN
        INSERT INTO SEGREGADA VALUES (IBAN, COMISION, IBAN_REFERENCIA);
    END IF;
    
    END;
    
    PROCEDURE CIERRE_CUENTA (IBANN VARCHAR2, TIPO_CUENTA VARCHAR2, IBAN_REFERENCIA VARCHAR2)
    IS
    
    FILA VARCHAR2(50);
    CUENTA_NO_ENCONTRADA EXCEPTION;
    TIPO_NO_VALIDO EXCEPTION;
    SALDO_NO_CERO EXCEPTION;
    
    BEGIN
    
    SELECT COUNT(*) INTO FILA
    FROM CUENTA
    WHERE IBAN = IBANN;
    
    IF FILA != '1' THEN
        RAISE CUENTA_NO_ENCONTRADA;
    END IF;
    IF TIPO_CUENTA != 'POOLED' AND TIPO_CUENTA != 'SEGREGADA' THEN
        RAISE TIPO_NO_VALIDO;
    END IF;
    
    IF TIPO_CUENTA LIKE 'SEGREGADA' THEN
        SELECT COUNT(*) INTO FILA
        FROM REFERENCIA
        WHERE IBAN = IBAN_REFERENCIA AND SALDO >0;
        
        IF FILA LIKE '1' THEN
            RAISE SALDO_NO_CERO; 
        END IF;
        
        UPDATE FINTECH
        SET ESTADO = 'BAJA', FECHA_CIERRE = SYSDATE;
    END IF;
    IF TIPO_CUENTA LIKE 'POOLED' THEN
        SELECT COUNT(*) INTO FILA
        FROM DEPOSITADA_EN
        WHERE POOLED_ACCOUNT_IBAN = IBANN AND REFERENCIA_IBAN = IBAN_REFERENCIA AND SALDO >0;
        
        IF FILA LIKE '0' THEN
            UPDATE FINTECH 
            SET ESTADO = 'BAJA', FECHA_CIERRE = SYSDATE;
        ELSE
            RAISE SALDO_NO_CERO;
        END IF;
    END IF;
    
    END;
    
    
END PK_GESTION_CUENTAS;