
insert into cliente values (6, '123456789N', 'FISICO', 'ACTIVO', 
    SYSDATE, NULL, 'ETSI', 'MALAGA', 29640, 'ESPAÑA');

INSERT INTO INDIVIDUAL VALUES (6, 'JOSE', 'PAN',SYSDATE);

COMMIT;



--CUENTAS


INSERT INTO CUENTA VALUES ('1', NULL);

INSERT INTO FINTECH VALUES ('1', 'ACTIVA', SYSDATE, NULL, 'SEGREGADA', 6);


INSERT INTO REFERENCIA VALUES ('123ES', 'EBURY', 'MALAGA', 'ESPAÑA', 100, SYSDATE,
    'ACTIVA', 'EUR');
    
COMMIT;

INSERT INTO SEGREGADA VALUES ('1', 5, '123ES');

COMMIT;

--PRUEBA PAQUETE CLIENTES

--DAR_ALTA


--PRUEBA OKAY DAR _ALTA
EXEC PK_GESTION_CLIENTES.DAR_ALTA (10, '79056080C', 'FISICO', 'ACTIVO', SYSDATE, NULL, 
    'CALLE','MALAGA', 29649, 'ESPAÑA', NULL, 'ALE', 'REQUE', SYSDATE);
    
--PRUEBA FALLA POR TIPO --> DAR_ALTA
EXEC PK_GESTION_CLIENTES.DAR_ALTA (15, '7905608C', 'NEPE', 'ACTIVO', SYSDATE, NULL, 'CALLE','MALAGA', 29649, 'ESPAÑA', NULL, 'ALE', 'REQUE', SYSDATE); 

--PRUEBA CLIENYE YA ESTA --> DAR_ALATA

EXEC PK_GESTION_CLIENTES.DAR_ALTA (10, '79056080C', 'FISICO', 'ACTIVO', SYSDATE, NULL,  'CALLE','MALAGA', 29649, 'ESPAÑA', NULL, 'ALE', 'REQUE', SYSDATE);

--MODIFICAR_CLIENTE

--PRUEBA CLIENTE MODIFICADO OKAY 

EXEC PK_GESTION_CLIENTES.MODIFICAR_CLIENTE (10, 'FISICO', 'ACTIVO', NULL, NULL, 'PASTEUR', 'MALAGA', 29640, 'ESPAÑA', NULL, 'ALEJANDRO', 'REQUENA', SYSDATE);


--PRUEBA CLIENTE NO EXISTENTE

EXEC PK_GESTION_CLIENTES.MODIFICAR_CLIENTE (100, 'FISICO', 'ACTIVO', NULL, NULL, 'PASTEUR', 'MALAGA', 29640, 'ESPAÑA', NULL, 'ALEJANDRO', 'REQUENA', SYSDATE);


--BAJA CLIENTE

--PRUEBA CLIENTE NO ENCONTRADO

EXEC PK_GESTION_CLIENTES.BAJA_CLIENTE (100);

--PRUEBA CUENTAS ABIERTAS

EXEC PK_GESTION_CLIENTES.BAJA_CLIENTE (6);

--PRUBEA 

EXEC PK_GESTION_CLIENTES.BAJA_CLIENTE (10);





--PAQUETE CUENTAS


--PRUEBA TIPO NO VALIDO

EXEC PK_GESTION_CUENTAS.ABRIR_CUENTA ('PRUEBA1ES', NULL, 'XD', 1, 'XD', '123ES', 5);

--PRUEBA CLIENTE BAJA

EXEC PK_GESTION_CUENTAS.ABRIR_CUENTA ('PRUEBA1ES', NULL, 'SEGREGADA', 10, 'SEGREGADA', '123ES', 5);

--PRUEBA REFERENCIA NO VALIDA

EXEC PK_GESTION_CUENTAS.ABRIR_CUENTA ('PRUEBA1ES', NULL, 'SEGREGADA', 10, 'SEGREGADA', '1234ES', 5);

--PRUEBA SEGREGADA OKAY

EXEC PK_GESTION_CUENTAS.ABRIR_CUENTA ('PRUEBA1ES', NULL, 'SEGREGADA', 1, 'SEGREGADA', '123ES', 5);


--PRUEBA POOLED OKAY

EXEC PK_GESTION_CUENTAS.ABRIR_CUENTA ('PRUEBA2ES', NULL, 'POOLED', 1, 'POOLED', '123ES', NULL);


--PRUEBA CIERRE CUENTA


