--EJERCICIO 2

--A

SELECT CL.IDENTIFICACION, F.IBAN, RE.SALDO, D.ABREVIATURA, D.CAMBIOEURO FROM CLIENTE CL, FINTECH F, REFERENCIA RE, DIVISA D
WHERE CL.ID = F.CLIENTE_ID AND RE.DIVISA_ABREVIATURA = D.ABREVIATURA ;


 CREATE VIEW V_SALDOS_INDIVIDUALES (IDENTIFICACION, IBAN, SALDO, ABREVIATURA, CAMBIOEURO)
 AS (SELECT );
 
 
 --B
 --CREACIÓN DE LAS SECUENCIAS
 
 CREATE SEQUENCE SQ_CLIENTE START WITH 1
 INCREMENT BY 10;
 
 CREATE SEQUENCE SQ_PERSONA START WITH 1
 INCREMENT BY 10;
 
 --MODIFICACIONES HECHAS 
 
 --C
 --CREACION DE TRIGGER
 
 
 