CREATE OR REPLACE PACKAGE PK_GESTION_CLIENTES AS
    PROCEDURE DAR_ALTA (IDE NUMBER, IDENTIFIACION NUMBER, TIPO VARCHAR2, ESTADO VARCHAR2,
    FECHA_ALTA DATE, FECHA_BAJA DATE, DIRECCION VARCHAR2, CIUDAD VARCHAR2, 
    CODIGO_POSTAL NUMBER, PAIS VARCHAR2, RAZON_SOCIAL VARCHAR2, NOMBRE VARCHAR2,
    APELLIDO VARCHAR2, FECHA_NAC DATE);
    
END PK_GESTION_CLIENTES;
/


CREATE OR REPLACE PACKAGE BODY PK_GESTION_CLIENTES AS
    PROCEDURE DAR_ALTA (IDE NUMBER, IDENTIFIACION NUMBER, TIPO VARCHAR2, ESTADO VARCHAR2,
    FECHA_ALTA DATE, FECHA_BAJA DATE, DIRECCION VARCHAR2, CIUDAD VARCHAR2, 
    CODIGO_POSTAL NUMBER, PAIS VARCHAR2, RAZON_SOCIAL VARCHAR2, NOMBRE VARCHAR2,
    APELLIDO VARCHAR2, FECHA_NAC DATE)
    IS 
    BEGIN 
    
    --HABRÍA QUE MIRAR EL TRATAMIENTO DE EXCEPCIONES
    --MIRAR SI EL CLIENTE YA ESTA
    --TIPO NO VALIDO?¿
        INSERT INTO CLIENTE VALUES (IDE, IDENTIFIACION, TIPO, ESTADO, FECHA_ALTA,
        FECHA_BAJA, DIRECCION, CIUDAD, CODIGO_POSTAL, PAIS);
        
        IF TIPO = 'FISICO' THEN
            INSERT INTO INDIVIDUAL VALUES (IDE, NOMBRE, APELLIDO, FECHA_NAC);
        END IF;
        
        IF TIPO = 'JURIDICO' THEN
            INSERT INTO EMPRESA VALUES (IDE, RAZON_SOCIAL);
        END IF;
    END;
END PK_GESTION_CLIENTES;