CREATE OR REPLACE PACKAGE PK_GESTION_CLIENTES AS
    PROCEDURE DAR_ALTA (IDE NUMBER, IDENTIFIACION VARCHAR2, TIPO VARCHAR2, ESTADO VARCHAR2,
    FECHA_ALTA DATE, FECHA_BAJA DATE, DIRECCION VARCHAR2, CIUDAD VARCHAR2, 
    CODIGO_POSTAL NUMBER, PAIS VARCHAR2, RAZON_SOCIAL VARCHAR2, NOMBRE VARCHAR2,
    APELLIDO VARCHAR2, FECHA_NAC DATE);
    
    PROCEDURE MODIFICAR_CLIENTE (IDE NUMBER, T VARCHAR2, E VARCHAR2,
    F_A DATE, F_B DATE, D VARCHAR2, C VARCHAR2, 
    C_P NUMBER, PA VARCHAR2, RAZ_SOC VARCHAR2, NOM VARCHAR2,
    APE VARCHAR2, FEC_NA DATE);

    PROCEDURE BAJA_CLIENTE (IDE NUMBER);
    
END PK_GESTION_CLIENTES;
/


CREATE OR REPLACE PACKAGE BODY PK_GESTION_CLIENTES AS
    PROCEDURE DAR_ALTA (IDE NUMBER, IDENTIFIACION VARCHAR2, TIPO VARCHAR2, ESTADO VARCHAR2,
    FECHA_ALTA DATE, FECHA_BAJA DATE, DIRECCION VARCHAR2, CIUDAD VARCHAR2, 
    CODIGO_POSTAL NUMBER, PAIS VARCHAR2, RAZON_SOCIAL VARCHAR2, NOMBRE VARCHAR2,
    APELLIDO VARCHAR2, FECHA_NAC DATE)
    IS 
        FILA VARCHAR(50);
        CLIENTE_YA_ENCONTRADO EXCEPTION;
        TIPO_NO_VALIDO EXCEPTION;
    BEGIN 
    
    
        SELECT COUNT(*) INTO FILA
        FROM CLIENTE
        WHERE ID = IDE;
        
        IF FILA LIKE '1' THEN
            RAISE CLIENTE_YA_ENCONTRADO;
        ELSE
            INSERT INTO CLIENTE VALUES (IDE, IDENTIFIACION, TIPO, ESTADO, FECHA_ALTA,
            FECHA_BAJA, DIRECCION, CIUDAD, CODIGO_POSTAL, PAIS);
        END IF;
        
        IF TIPO != 'FISICO' AND TIPO != 'JURIDICO' THEN
            RAISE TIPO_NO_VALIDO;
        END IF;
        
        IF TIPO = 'FISICO' THEN
            INSERT INTO INDIVIDUAL VALUES (IDE, NOMBRE, APELLIDO, FECHA_NAC);
        END IF;
        
        IF TIPO = 'JURIDICO' THEN
            INSERT INTO EMPRESA VALUES (IDE, RAZON_SOCIAL);
        END IF;
    END;

    
    PROCEDURE MODIFICAR_CLIENTE (IDE NUMBER, T VARCHAR2, E VARCHAR2,
    F_A DATE, F_B DATE, D VARCHAR2, C VARCHAR2, 
    C_P NUMBER, PA VARCHAR2, RAZ_SOC VARCHAR2, NOM VARCHAR2,
    APE VARCHAR2, FEC_NA DATE)
    IS
        FILA VARCHAR(50);
        CLIENTE_NO_ENCONTRADO EXCEPTION;
    
    BEGIN 

    
        SELECT COUNT(*) INTO FILA
        FROM CLIENTE
        WHERE ID = IDE;
        
        IF FILA LIKE '1' THEN
        
            UPDATE CLIENTE 
            SET ESTADO = E, DIRECCION = D, CIUDAD = C, CODIGOPOSTAL = C_P, PAIS = PA
            WHERE ID = IDE;
        ELSE
            RAISE CLIENTE_NO_ENCONTRADO;
        END IF;
        
        IF T = 'FISICO' THEN
            UPDATE INDIVIDUAL
            SET NOMBRE = NOM, APELLIDO = APE, FECHA_NACIMIENTO = FEC_NA
            WHERE ID = IDE;
        END IF;
        
        IF T = 'JURIDICO' THEN
            UPDATE EMPRESA
            SET RAZON_SOCIAL = RAZ_SOC
            WHERE ID = IDE;
        END IF;
    
    END;
    
    
    PROCEDURE BAJA_CLIENTE (IDE NUMBER)
    IS 
        FILA VARCHAR(50);
        FILA_CUENTA VARCHAR(50);
        CLIENTE_NO_ENCONTRADO EXCEPTION;
        CUENTAS_ABIERTAS EXCEPTION;
    BEGIN
    
        
        SELECT COUNT(*) INTO FILA
        FROM CLIENTE
        WHERE ID = IDE;
        
        SELECT COUNT(*) INTO FILA_CUENTA
        FROM FINTECH
        WHERE CLIENTE_ID = IDE AND ESTADO != 'BAJA';
        
        IF FILA != '1' THEN
            RAISE CLIENTE_NO_ENCONTRADO;
        END IF;
        
        IF FILA_CUENTA != '0' THEN
            RAISE CUENTAS_ABIERTAS;
        END IF;
           
        UPDATE CLIENTE
        SET ESTADO = 'BAJA', FECHA_BAJA = SYSDATE
        WHERE ID = IDE;
    
    END;
    
END PK_GESTION_CLIENTES;